### ISSUE TITLE
Add timestamp to the files?

### ISSUE THREAD

**Issue by nstauffer** [nstauffer/balanced-design-tool#17]
There's already a datestamp, but a timestamp might be useful too for multiple designs downloaded at once.

Probably just add it to the .zip filename and not its contents.

**Comment by smccord** [comment]
Yes, the underscore is a good idea. I still think we should used dashes per ISO 8601 as well, but I'll leave that one up to you.

**Comment by nstauffer** [comment]
I implemented the format:
%Y-%m-%dT%H%MZ
Time is in UTC (hence the Z). I'm a little iffy on having _ and - in filenames, but I'm rolling with it for now
